#!/bin/sh
set -eu

RUNLEVEL="${1:-}"

printf "[I]: Runlevel: %s\n" "${RUNLEVEL}"

## Functions {{{

do_mount_fs() {
    # /proc
    if ! [ -e /proc/stat ]; then
        mount -t proc proc /proc
    fi

    # /run
    if ! grep ' /run ' /proc/mounts >/dev/null 2>&1; then
        mount -t tmpfs -o exec none /run
    else
        mount -o remount,exec /run
    fi

    # /var
    if [ -e /etc/fstab ]; then
        if grep '/var' /etc/fstab >/dev/null 2>&1; then
            mount /var || :
        fi
    fi
}

do_s6_svscan() {
    if ! [ -d /run/service ]; then
        mkdir /run/service
    fi

    {
        s6-svscan /run/service 2>&1 | \
            s6-log -b -- t n10 s1000000 /var/log/s6-svscan
    } &

    # Add s6-svscan and s6-log to sendsigs.omit
    if ! [ -d /run/sendsigs.omit.d ]; then
        mkdir /run/sendsigs.omit.d
    fi
    pgrep -f 's6-svscan /run/service'       >/run/sendsigs.omit.d/s6-svscan
    pgrep -f 's6-log .* /var/log/s6-svscan' >/run/sendsigs.omit.d/s6-svscan-log
}

do_s6_rc_init() {
    [ -d /etc/s6/rc ] || mkdir -p /etc/s6/rc
    [ -d /etc/s6/sv ] || mkdir -p /etc/s6/sv

    if ! [ -e /etc/s6/rc/compiled ]; then
        s6-db-reload
    fi

    s6-rc-init -c /etc/s6/rc/compiled -l /run/s6-rc /run/service
}

do_s6_svscan_terminate() { s6-svscanctl -t /run/service || : ; }

do_init_d_rc() {
    s6-rc -l /run/s6-rc -a list | \
        grep '^rc[Ss0-6]$' | xargs -d'\n' s6-rc -v2 -l /run/s6-rc -d change

    s6-rc -v2 -l /run/s6-rc -u change rc"${1}"
}

do_off()    { poweroff -d -h; }
do_reboot() { reboot   -d -h; }

## }}}

case "${RUNLEVEL}" in
    "S")
        do_mount_fs
        do_s6_svscan
        do_s6_rc_init
        do_init_d_rc "${RUNLEVEL}"
        ;;
    "0")
        do_s6_svscan_terminate
        s6-rc-run-init_d "${RUNLEVEL}"
        do_off
        ;;
    "6")
        do_s6_svscan_terminate
        s6-rc-run-init_d "${RUNLEVEL}"
        do_reboot
        ;;
    "1"|"2"|"3"|"4"|"5")
        do_init_d_rc "${RUNLEVEL}"
        ;;
    *)
        telinit 6
        ;;
esac

exit 0

# vim: sw=4 ts=4 et
