#!/bin/sh
set -eu

RUNLEVEL="${1:-}"
[ -n "${RUNLEVEL}" ] || {
    printf "[E]: No runlevel!\n"
    exit 1
}

if [ "${RUNLEVEL}" = "s" ]; then
    RUNLEVEL="S"
fi

RC_DIR="/etc/init.d/rc${RUNLEVEL}.d"

if stat -t "${RC_DIR}"/K* >/dev/null 2>&1; then
    for SV in "${RC_DIR}"/K*; do
        "${SV}" stop
    done
fi

if stat -t "${RC_DIR}"/S* >/dev/null 2>&1; then
    for SV in "${RC_DIR}"/S*; do
        "${SV}" start
    done
fi
