#!/bin/sh
set -eu

RUNLEVEL="${1:-}"
[ -n "${RUNLEVEL}" ] || {
    printf "[E]: No runlevel!\n"
    exit 1
}

if [ "${RUNLEVEL}" = "s" ]; then
    RUNLEVEL="S"
fi

RC_DIR="/etc/rc${RUNLEVEL}.d"

if stat -t "${RC_DIR}"/K* >/dev/null 2>&1; then
    for SV in "${RC_DIR}"/K*; do
        "${SV}" stop
    done
fi

S_ACTION="start"
if [ "${RUNLEVEL}" = "0" ] || [ "${RUNLEVEL}" = "6" ]; then
    S_ACTION="stop"
fi

if stat -t "${RC_DIR}"/S* >/dev/null 2>&1; then
    for SV in "${RC_DIR}"/S*; do
        "${SV}" "${S_ACTION}"
    done
fi
